### PR TITLE
elementary processing of trivial expressions

### PR DESCRIPTION
**Pull request by mmatera**
This PR adds benchmarks to 
* expressions that require almost no evaluation, like the evaluation of atoms, or the evaluation that consists of just accessing the attributes in a definition. 
* Pattern matching and rule applying.

### CODE REVIEW

**Review by TiagoCavalcante — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
It looks as though this may be useful in the future. Right now I haven't been able to figure out how to benchmark this against 4.0.0 and I don't want to spend the time right now to figure out what the deal is.

I am a saddened that every time I try to use mathics-benchmark to get an answer to a simple question:  like have we improved at all?  I am faced with trying to figure out how to run stuff or workaround some problem where I have to first figure out what the problem is.

On the positive side, I am glad to see that at least we are starting to get benchmarks written down in one place (rather than hack doctests and timing hacks on top of doctests), so that at some point in the future we will have a methodology for answering questions like have we improved?

**Comment by TiagoCavalcante** [comment]
@rocky I recommend running the `run-all` benchmark against `master` and `4.0.0 SHA here`, that's why I recommend to tag the versions of mathics-core.

**Comment by TiagoCavalcante** [comment]
@rocky this should work: `mathics-bench-compare run-all 4.0.0`, but I'm getting an error related to Cython (as in old mathics-core versions it couldn't be skipped).

**Comment by rocky** [comment]
Ok. Then I think what we should do is create a branch off of 4.0.0 that doesn't skip removing Cython. And we can use that tag instead.

**Pull request merged**
